name: onPR

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: show current head ref
        run: echo ${{ github.head_ref }}
  
      - name: Increment devBuild
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=devBuild -q -DforceStdout)
          NEW_VERSION=$((CURRENT_VERSION + 1))
          mvn versions:set-property -Dproperty=devBuild -DnewVersion=$NEW_VERSION
          
      - name: Setup git user
        uses: fregante/setup-git-user@v1

      - name: Commit change
        run: |
          git add .
          git commit -am "⬆️ Increment devBuild"
          git push
