name: Update QA Build Version

on:
  push:
    branches:    
      - 'testing/develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Increment QA Build Version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=qaBuild -q -DforceStdout)
          NEW_VERSION=$((CURRENT_VERSION + 1))
          mvn versions:set-property -Dproperty=qaBuild -DnewVersion=$NEW_VERSION -DgenerateBackupPoms=false
          
      - name: Setup git user
        uses: fregante/setup-git-user@v1

      - name: Commit Change
        run: |
          git add .
          git commit -am "⬆️ Increment QA Build to $NEW_VERSION"
          git push
