name: Update QA Build Version

on:
  push:
    branches:    
      - 'testing/develop'

jobs:
  UPDATE_QA_BUILD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup git user
        uses: fregante/setup-git-user@v1
     
      - name: execute file
        run: |
          cd src/main/resources
          VERSION=$(cat qaBuild.txt)
          ((VERSION++))
          echo $VERSION > qaBuild.txt
          git add .
          git commit -am "⬆️ Increment QA Build to $VERSION"
          git push
