name: onPR

on:
  pull_request:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
  
      - name: Increment devBuild
        run: |
          mvn versions:set-property -Dproperty=devBuild -DnewVersion=\$((\$(mvn help:evaluate -Dexpression=devBuild -q -DforceStdout)+1))

      - name: Setup git user
        uses: fregante/setup-git-user@v1
        
      - name: Commit changes
        run: |          
          git add .
          git commit -am "⬆️ Increment devBuild"
          git push
