name: Update QA Build Version

on:
  push:
    branches:    
      - 'testing/develop'

jobs:
  UPDATE_QA_BUILD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: current file
        run: |
          echo pwd
      - name: execute file
        run: |
          cd src/main/resources && ./test.sh
          
      - name: Setup git user
        uses: fregante/setup-git-user@v1

      - name: commit changes
        run: |
          git add .
          git commit -am "⬆️ Increment QA Build to $NEW_VERSION"
          git push

