name: Update QA Build Version

on:
  push:
    branches:    
      - 'testing/develop'

jobs:
  UPDATE_QA_BUILD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup git user
        uses: fregante/setup-git-user@v1
        
      - name: Increase number
        run: |
          # Read the number from the file
          num=$(cat src/main/resources/qaBuild.txt)
          echo "Current number is $num"
      
          # Increment the number
          num=$((num + 1))
          echo "New number is $num"
      
          # Write the new number back to the file
          echo $num > src/main/resources/qaBuild.txt
          echo "Done. commit changes"
          git add .
          git commit -am "⬆️ Increment QA Build to $num"
          git push
          
